- added local nginx support - added "group" for permissions

diff --git a/wploy b/wploy
--- a/wploy
+++ b/wploy
@@ -3,21 +3,6 @@
 # Script to for basic Wordpress site deployment.
 #
 
-checkintent() {
-	if [[ $i && ${i} ]] ; then
-		migrate
-	else
-		echo "I really need to know what you want to do here..."
-		recheck
-	fi
-}
-
-recheck() {
-	read newintent
-	i=$newintent
-	checkintent
-}
-
 in_array() {
 	local haystack=${1}[@]
 	local needle=${2}
@@ -57,97 +42,127 @@ continueprompt() {
 }
 
 migrate() {
-	if in_array cmds "${i}"; then
-		src_id="${i::1}"
-		dest_id="${i: -1}"
+	if [[ $dest_id == "p" ]]; then
+		echo "\n---------------------------------------------------------------------------"
+		echo "You are pushing your project to the production server!"
+		echo "Are you absolutely sure you want to do this?? [y/N]"
+		echo "---------------------------------------------------------------------------\n"
+		continueprompt
+	fi
 
-		SRC_HOST=${src_id}_host
-		SRC_SSH_USER=${src_id}_ssh_user
-		SRC_SSH_PASS=${src_id}_ssh_pass
-		SRC_DB=${src_id}_db
-		SRC_DB_USER=${src_id}_db_user
-		SRC_DB_PASS=${src_id}_db_pass
-		SRC_PATH=${src_id}_path
-		SRC_URL=${src_id}_url
-
-		DEST_HOST=${dest_id}_host
-		DEST_SSH_USER=${dest_id}_ssh_user
-		DEST_SSH_PASS=${dest_id}_ssh_pass
-		DEST_DB=${dest_id}_db
-		DEST_DB_USER=${dest_id}_db_user
-		DEST_DB_PASS=${dest_id}_db_pass
-		DEST_PATH=${dest_id}_path
-		DEST_URL=${dest_id}_url
-
-		if [[ $dest_id == "p" ]]; then
-			echo "\n---------------------------------------------------------------------------"
-			echo "You are pushing your project to the production server!"
-			echo "Are you absolutely sure you want to do this?? [y/N]"
-			echo "---------------------------------------------------------------------------\n"
-			continueprompt
-		fi
-
-		if [[ $src_id == "l" ]]; then
-			#first, run out grunt build script
+	if [[ $src_id == "l" ]]; then
+		if [ -d $SITES_DIR/$project_id/web/node_modules ]; then #check if grunt exists
+			#first, run out grunt build script - if grunt exists for this project
 			grunt build
-
-			#export Database
-			mysqldump -u $l_db_user -p$l_db_pass $l_db > $l_db.sql
-
-			#find and replace old URLs in SQL file
-			sed -i '' "s/${!SRC_URL}/${!DEST_URL}/g" ${!SRC_PATH}${l_db}.sql
-
-			#find and replace old Database Info in wp-config.php file
-			sed -i.backup -e"s/define('DB_NAME', '${!SRC_DB}');/define('DB_NAME', '${!DEST_DB}');/g" -e"s/define('DB_USER', '${!SRC_DB_USER}');/define('DB_USER', '${!DEST_DB_USER}');/g" -e"s/define('DB_PASSWORD', '${!SRC_DB_PASS}');/define('DB_PASSWORD', '${!DEST_DB_PASS}');/g" ${!SRC_PATH}wp-config.php
-
-			#move the site files to remote server
-			rsync -avO --exclude-from 'wploy-excludes.txt' -e ssh $l_path ${!DEST_SSH_USER}@${!DEST_HOST}:${!DEST_PATH}
-
-			#remove database dump from working directory
-			rm ${!SRC_PATH}${l_db}.sql
-
-			#replace the altered wp-config with the backup on the local host
-			mv ${!SRC_PATH}wp-config.php.backup ${!SRC_PATH}wp-config.php
-
-			#log into remote host, import database and remove the backup wp-config file
-			ssh root@${!DEST_HOST} "mysql -u ${!DEST_DB_USER} -p${!DEST_DB_PASS} ${!DEST_DB} < /srv/users/${!DEST_SSH_USER}/${!DEST_PATH}$l_db.sql; rm /srv/users/${!DEST_SSH_USER}/${!DEST_PATH}$l_db.sql; rm /srv/users/${!DEST_SSH_USER}/${!DEST_PATH}wp-config.php.backup"
-		elif [ $src_id == "s" ] || [ $src_id == "p" ]; then
-ssh root@${!SRC_HOST} /bin/bash << EOF
-mysqldump -u ${!SRC_DB_USER} -p${!SRC_DB_PASS} ${!SRC_DB} > /srv/users/${!SRC_SSH_USER}/${!SRC_PATH}${!SRC_DB}.sql
-sed -i "s/${!SRC_URL}/${!DEST_URL}/g" /srv/users/${!SRC_SSH_USER}/${!SRC_PATH}${!SRC_DB}.sql
-sed -i.backup -e"s/define('DB_NAME', '${!SRC_DB}');/define('DB_NAME', '${!DEST_DB}');/g" -e"s/define('DB_USER', '${!SRC_DB_USER}');/define('DB_USER', '${!DEST_DB_USER}');/g" -e"s/define('DB_PASSWORD', '${!SRC_DB_PASS}');/define('DB_PASSWORD', '${!DEST_DB_PASS}');/g" /srv/users/${!SRC_SSH_USER}/${!SRC_PATH}wp-config.php
-EOF
-			if [[ $dest_id == "l" ]]; then
-				rsync -avO --exclude-from 'wploy-excludes.txt' -e ssh ${!SRC_SSH_USER}@${!SRC_HOST}:${!SRC_PATH} $l_path
-			else
-				rsync -avO -e ssh ${l_path}wploy-excludes.txt ${!SRC_SSH_USER}@${!SRC_HOST}:${!SRC_PATH}
-ssh root@${!SRC_HOST} /bin/bash << EOF
-rsync -avO --exclude-from '/srv/users/'${!SRC_SSH_USER}'/'${!SRC_PATH}'wploy-excludes.txt' /srv/users/${!SRC_SSH_USER}/${!SRC_PATH} root@${!DEST_HOST}:/srv/users/${!DEST_SSH_USER}/${!DEST_PATH}
-rm /srv/users/${!SRC_SSH_USER}/${!SRC_PATH}wploy-excludes.txt
-EOF
-			fi
-			ssh root@${!SRC_HOST} "rm /srv/users/${!SRC_SSH_USER}/${!SRC_PATH}${!SRC_DB}.sql; mv /srv/users/${!SRC_SSH_USER}/${!SRC_PATH}wp-config.php.backup /srv/users/${!SRC_SSH_USER}/${!SRC_PATH}wp-config.php"
-			if [[ $dest_id == "l" ]]; then
-				mysql -u $l_db_user -p$l_db_pass $l_db < ${l_path}${!SRC_DB}.sql; rm ${l_path}${!SRC_DB}.sql
-				rm ${l_path}wp-config.php.backup
-			else
-				ssh root@${!DEST_HOST} "mysql -u ${!DEST_DB_USER} -p${!DEST_DB_PASS} ${!DEST_DB} < /srv/users/${!DEST_SSH_USER}/${!DEST_PATH}${!SRC_DB}.sql; rm /srv/users/${!DEST_SSH_USER}/${!DEST_PATH}${!SRC_DB}.sql; rm /srv/users/${!DEST_SSH_USER}/${!DEST_PATH}wp-config.php.backup"
-			fi
-			if [[ $dest_id == "s" ]]; then
-				echo "activate code freeze"
-				# ssh root@${!SRC_HOST} "wp plugin activate code-freeze"
-			fi
 		fi
 
-		# echo ${!SRC_HOST}
-	else
-		echo "I didn't understand what you're trying to do..."
-		recheck
+		#export Database
+		mysqldump -u $l_db_user -p$l_db_pass $l_db > ${!SRC_PATH}${l_db}.sql
+
+		#find and replace old URLs in SQL file
+		sed -i '' "s/${!SRC_URL}/${!DEST_URL}/g" ${!SRC_PATH}${l_db}.sql
+
+		#find and replace old Database Info in wp-config.php file
+		sed -i.backup -e"s/define('DB_NAME', '${!SRC_DB}');/define('DB_NAME', '${!DEST_DB}');/g" -e"s/define('DB_USER', '${!SRC_DB_USER}');/define('DB_USER', '${!DEST_DB_USER}');/g" -e"s/define('DB_PASSWORD', '${!SRC_DB_PASS}');/define('DB_PASSWORD', '${!DEST_DB_PASS}');/g" -e"s#define( 'WPCACHEHOME', '.*' );#define( 'WPCACHEHOME', '${!DEST_PATH}wp-content/plugins/wp-super-cache/' );#g" ${!SRC_PATH}wp-config.php
+
+
+		#move the site files to remote server
+		rsync -avO --exclude-from 'wploy-excludes.txt' -e ssh $l_path ${!DEST_SSH_USER}@${!DEST_HOST}:${!DEST_PATH}
+
+		#remove database dump from working directory
+		rm ${!SRC_PATH}${l_db}.sql
+
+		#replace the altered wp-config with the backup on the local host
+		mv ${!SRC_PATH}wp-config.php.backup ${!SRC_PATH}wp-config.php
+
+		#log into remote host, import database and remove the backup wp-config file && set owner for site files
+		ssh ${!DEST_SSH_USER}@${!DEST_HOST} "mysql -u ${!DEST_DB_USER} -p${!DEST_DB_PASS} ${!DEST_DB} < ${!DEST_PATH}$l_db.sql; rm ${!DEST_PATH}$l_db.sql; rm ${!DEST_PATH}wp-config.php.backup; chown -R ${!DEST_OWNER}:${!DEST_GROUP} ${!DEST_PATH}"
+
+	elif [ $src_id == "s" ] || [ $src_id == "p" ]; then
+ssh ${!SRC_SSH_USER}@${!SRC_HOST} /bin/bash << EOF
+mysqldump -u ${!SRC_DB_USER} -p${!SRC_DB_PASS} ${!SRC_DB} > ${!SRC_PATH}${!SRC_DB}.sql
+sed -i "s/${!SRC_URL}/${!DEST_URL}/g" ${!SRC_PATH}${!SRC_DB}.sql
+sed -i.backup -e"s/define('DB_NAME', '${!SRC_DB}');/define('DB_NAME', '${!DEST_DB}');/g" -e"s/define('DB_USER', '${!SRC_DB_USER}');/define('DB_USER', '${!DEST_DB_USER}');/g" -e"s/define('DB_PASSWORD', '${!SRC_DB_PASS}');/define('DB_PASSWORD', '${!DEST_DB_PASS}');/g" -e"s#define( 'WPCACHEHOME', '.*' );#define( 'WPCACHEHOME', '${!DEST_PATH}wp-content/plugins/wp-super-cache/' );#g" ${!SRC_PATH}wp-config.php
+EOF
+		if [[ $dest_id == "l" ]]; then
+			rsync -avO --exclude-from 'wploy-excludes.txt' -e ssh ${!SRC_SSH_USER}@${!SRC_HOST}:${!SRC_PATH} $l_path
+		else
+			rsync -avO -e ssh ${l_path}wploy-excludes.txt ${!SRC_SSH_USER}@${!SRC_HOST}:${!SRC_PATH}
+ssh ${!SRC_SSH_USER}@${!SRC_HOST} /bin/bash << EOF
+rsync -avO --exclude-from ${!SRC_PATH}'wploy-excludes.txt' ${!SRC_PATH} ${!DEST_SSH_USER}@${!DEST_HOST}:${!DEST_PATH}
+rm ${!SRC_PATH}wploy-excludes.txt
+EOF
+		fi
+		ssh ${!SRC_SSH_USER}@${!SRC_HOST} "sudo rm ${!SRC_PATH}${!SRC_DB}.sql; mv ${!SRC_PATH}wp-config.php.backup ${!SRC_PATH}wp-config.php"
+		if [[ $dest_id == "l" ]]; then
+			# change ownership of files in new environment
+			sudo chown -R ${!DEST_OWNER}:${!DEST_GROUP} ${!DEST_PATH}
+
+			mysql -u $l_db_user -p$l_db_pass $l_db < ${l_path}${!SRC_DB}.sql; sudo rm ${l_path}${!SRC_DB}.sql
+			sudo rm ${l_path}wp-config.php.backup
+		else
+			ssh ${!DEST_SSH_USER}@${!DEST_HOST} "mysql -u ${!DEST_DB_USER} -p${!DEST_DB_PASS} ${!DEST_DB} < ${!DEST_PATH}${!SRC_DB}.sql; sudo rm ${!DEST_PATH}${!SRC_DB}.sql; sudo rm ${!DEST_PATH}wp-config.php.backup; sudo chown -R ${!DEST_OWNER}:${!DEST_GROUP} ${!DEST_PATH}"
+		fi
+		if [[ $dest_id == "s" ]]; then
+			# echo "activate code freeze"
+			ssh ${!SRC_SSH_USER}@${!SRC_HOST} "cd ${!SRC_PATH}; wp plugin activate code-freeze --allow-root"
+		fi
 	fi
 }
 
-if [[ $1 && ${1} ]] ; then
-	project_id=$1
+setupstaging() {
+	echo "\nLet's get your staging area set up!\n"
+
+	# Go ahead and set up a staging area on Serverpilot
+ 	NEWSTAGEAPP_OBJ=$(curl https://api.serverpilot.io/v1/apps -u $CLIENTID:$APIKEY -H "Content-Type: application/json" -d '{"name": "'$project_id'xstaging", "sysuserid": "'$STAGING_SYSID'", "runtime": "php5.4", "domains": ["'$project_id'.staging.yellowberri.com"]}')
+ 	stage_app_id=$(echo $NEWSTAGEAPP_OBJ | jq '.data | .id' | sed s/\"//g)
+	curl https://api.serverpilot.io/v1/dbs -u $CLIENTID:$APIKEY -H "Content-Type: application/json" -d '{"appid": "'$stage_app_id'", "name": "'$project_id'_db", "user": {"name": "'${project_id:0:5}'_'$SECRET_CODE'", "password": "'$LIVE_DB_PASS_PREFIX''$SECRET_CODE'"}}'
+
+	# set up keys from local to staging
+	cat ~/.ssh/id_rsa.pub | ssh ${STAGING_SSH_USER}@${STAGING_HOST} "mkdir -p ~/.ssh && cat >>  ~/.ssh/authorized_keys"
+	# we gotta set up our keys from staging to production
+	ssh ${STAGING_SSH_USER}@${STAGING_HOST} "ssh-keygen -t id_rsa; ssh-copy-id ${PROD_SSH_USER}@${PROD_HOST}"
+}
+
+setupprod() {
+	echo "\nLet's get that production server ssh set up!\n"
+	# first, set up keys from local to production
+	cat ~/.ssh/id_rsa.pub | ssh ${PROD_SSH_USER}@${PROD_HOST} "mkdir -p ~/.ssh && cat >>  ~/.ssh/authorized_keys"
+
+	# we gotta set up our keys from production to staging as well -- also need to set up wp-cli on production server so we can enable code freeze when we need to
+	ssh ${PROD_SSH_USER}@${PROD_HOST} "ssh-keygen -t id_rsa; ssh-copy-id ${STAGING_SSH_USER}@${STAGING_HOST}; curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar; chmod +x wp-cli.phar; sudo mv wp-cli.phar /usr/local/bin/wp"
+}
+
+project_id=""
+purpose=""
+intent=""
+remote_id=""
+
+# First, we want to set up some help documentation
+while getopts ":h" opt; do
+	case ${opt} in
+		h )
+			echo "Usage:"
+			echo "	wploy -h"
+			echo "	wpinit <project_id> [-m <l2s><l2p><s2p><p2s>]"
+			echo "	wpinit <project_id> [-s <staging><prod>]"
+			exit 0
+			;;
+		\? )
+			echo "Invalid Option: -$OPTARG" 1>&2
+			exit 1
+			;;
+	esac
+done
+shift $((OPTIND -1))
+
+project_id=$1; shift
+
+# load wp-init config file
+# . wpinit.config
+source ${BASH_SOURCE[0]/%wploy/wpinit.config}
+
+if [[ $project_id && ${project_id} ]] ; then
 	# load project wploy config file
 	# . wploy.config
 	source ~/Sites/$project_id/web/wploy.config
@@ -158,11 +173,60 @@ if [[ $1 && ${1} ]] ; then
 	#make sure were in the right directory and everything...
 	cd ~/Sites/$project_id/web/
 
-	if [[ $2 && ${2} ]] ; then
-		i=$2
-	fi
+	while getopts ":s:m:" opt; do
+		case $opt in
+			s )
+				remote_id=$OPTARG
+				if [ $remote_id == "staging" ] ; then
+					setupstaging
+				elif [ $remote_id == "prod" ] ; then
+					setupprod
+				else
+					echo "I don't recognize the target server..."
+					exit 1
+				fi
+				;;
+			m )
+				intent=$OPTARG
+				if in_array cmds "${intent}"; then
+					src_id="${intent::1}"
+					dest_id="${intent: -1}"
 
-	checkintent
+					SRC_HOST=${src_id}_host
+					SRC_SSH_USER=${src_id}_ssh_user
+					SRC_SSH_PASS=${src_id}_ssh_pass
+					SRC_DB=${src_id}_db
+					SRC_DB_USER=${src_id}_db_user
+					SRC_DB_PASS=${src_id}_db_pass
+					SRC_PATH=${src_id}_path
+					SRC_URL=${src_id}_url
+
+					DEST_HOST=${dest_id}_host
+					DEST_SSH_USER=${dest_id}_ssh_user
+					DEST_SSH_PASS=${dest_id}_ssh_pass
+					DEST_DB=${dest_id}_db
+					DEST_DB_USER=${dest_id}_db_user
+					DEST_DB_PASS=${dest_id}_db_pass
+					DEST_PATH=${dest_id}_path
+					DEST_URL=${dest_id}_url
+					DEST_OWNER=${dest_id}_owner
+					DEST_GROUP=${dest_id}_group
+				else
+					echo "I didn't understand what you're trying to do..."
+					exit 1
+				fi
+				# checkintent
+				migrate
+				;;
+			\? )
+				echo "Invalid option: -$OPTARG" 1>&2
+				;;
+			: )
+				echo "Invalid option: $OPTARG requires an argument" 1>&2
+				;;
+		esac
+		shift $((OPTIND -1))
+	done
 else
 	echo "Project ID not specified! Stop wasting my time."
 	exit
